INSERT INTO CLIENTS VALUES (1, 'user1@gmail.com','Кузнецов',CURDATE(), TRUE);
INSERT INTO CLIENTS VALUES (2, 'user2@gmail.com','Хорошилов',CURDATE(), TRUE);
INSERT INTO ORDERS VALUES (1, 1,500,CURDATE());
INSERT INTO ORDERS VALUES (2, 2,1500,CURDATE());
