CREATE TABLE CLIENTS (
clientId INTEGER NOT NULL AUTO_INCREMENT,
email VARCHAR(250) NOT NULL,
surname VARCHAR(250) NOT NULL,
BIRTHDAY DATE NOT NULL,
MALE BOOLEAN DEFAULT FALSE,
PRIMARY KEY (clientId)
);
CREATE TABLE ORDERS (
orderId INTEGER NOT NULL AUTO_INCREMENT,
clientId INTEGER NOT NULL,
price INTEGER NOT NULL,
orderTime DATE NOT NULL,
PRIMARY KEY (orderId)
);