CREATE TABLE CLIENTS (
clientId INTEGER AUTO_INCREMENT  PRIMARY KEY,
email VARCHAR(250) NOT NULL,
surname VARCHAR(250) NOT NULL,
BIRTHDAY DATE NOT NULL,
MALE BOOLEAN DEFAULT FALSE
);
CREATE TABLE ORDERS (
orderId INTEGER AUTO_INCREMENT  PRIMARY KEY,
clientId INTEGER NOT NULL,
price INTEGER NOT NULL,
orderTime DATE NOT NULL
);